# 1. Build this image:
# docker build -t peopleoid/kubernetes:hello-world docker-images/hello-world/

# 2. Push to Docker Hub:
# docker push peopleoid/kubernetes:hello-world

# 3. OR, just run the script:
# docker-images/hello-world/update.sh

FROM nginx
COPY index.html /usr/share/nginx/html
