# 1. Build this image:
# docker build -t peopleoid/kubernetes:hello-world-v3 docker-images/hello-world-v3/

# 2. Push to Docker Hub:
# docker push peopleoid/kubernetes:hello-world-v3

# 3. OR, just run the script:
# docker-images/hello-world-v3/update.sh

FROM nginx
COPY index.html /usr/share/nginx/html
