# 1. Build this image:
# docker build -t peopleoid/kubernetes:hello-world-v2 docker-images/hello-world-v2/

# 2. Push to Docker Hub:
# docker push peopleoid/kubernetes:hello-world-v2

# 3. OR, just run the script:
# docker-images/hello-world-v2/update.sh

FROM nginx
COPY index.html /usr/share/nginx/html
