apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: engineering
  labels:
    app: customer
spec:
  replicas: 2
  template:
    metadata:
      name: customer
      labels:
        app: customer
        environment: test
        tier: backend
        department: engineering
    spec:
      containers:
        - name: customer
          image: peopleoid/kubernetes:customer-v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              # Path to target for liveness checks
              path: "/health"

              # Port needs to be the same as container port
              port: 8080

            # Number of seconds after the container has started before liveness probes are initiated.
            # So, here we say only kick off liveness probe checks after 5 seconds.
            initialDelaySeconds: 5

            # Number of seconds after which the probe times out. Defaults to 1 second
            timeoutSeconds: 1

            # Minimum consecutive failures for the probe to be considered failed after having succeeded.
            # Defaults to 3.
            failureThreshold: 3

            # How often (in seconds) to perform the probe
            periodSeconds: 5
          env:
            - name: ORDER_SERVICE
              value: "order"
#            - name: KILL_IN_SECONDS
#              value: "30"
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-node
  namespace: engineering
spec:
  selector:
    app: customer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: engineering
spec:
  selector:
    app: customer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
