apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: engineering
  labels:
    app: customer
spec:
  replicas: 2
  template:
    metadata:
      name: customer
      labels:
        app: customer
        environment: test
        tier: backend
        department: engineering
    spec:
      containers:
        - name: customer
          image: milanobrenovic/kubernetes:customer-v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5
          env:
            - name: ORDER_SERVICE
              value: "order"
#            - name: KILL_IN_SECONDS
#              value: "30"
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-node
  namespace: engineering
spec:
  selector:
    app: customer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: engineering
spec:
  selector:
    app: customer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
