apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: engineering
  labels:
    app: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        environment: test
        tier: frontend
        department: engineering
    spec:
      containers:
        - name: frontend
          image: milanobrenovic/kubernetes:frontend-v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: engineering
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
