apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath
  labels:
    app: hostpath
spec:
  replicas: 1
  template:
    metadata:
      name: hostpath
      labels:
        app: hostpath
    spec:
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
      containers:
        - name: hostpath
          volumeMounts:
            - mountPath: /var/log
              name: var-log
              readOnly: true
          image: busybox
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            - "sleep"
            - "3600"
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: hostpath
