apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
  labels:
    app: job
spec:
  replicas: 1
  template:
    metadata:
      name: job
      labels:
        app: job
    spec:
      containers:
        - name: job
          image: busybox
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: job
