apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
    environment: dev
    tier: backend
    department: engineering
spec:
  containers:
    - name: hello-world
      image: peopleoid/kubernetes:hello-world
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
    name: blue
    environment: test
spec:
  containers:
    - name: blue
      image: peopleoid/kubernetes:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      imagePullPolicy: Always
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: green
  labels:
    name: green
    environment: test
spec:
  containers:
    - name: green
      image: peopleoid/kubernetes:green
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      imagePullPolicy: Always
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: labels-and-selector
spec:
  selector:
    name: green
    environment: test
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
