apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: docker-hub-private
      containers:
        - name: myapp
          image: milanobrenovic/private-frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: myapp
