apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
  labels:
    app: secrets
spec:
  replicas: 1
  template:
    metadata:
      name: secrets
      labels:
        app: secrets
    spec:
      volumes:
        - name: secret-1
          secret:
            secretName: mysecret
      containers:
        - name: secrets
          image: busybox
          volumeMounts:
            - mountPath: /etc/secrets
              name: secret-1
          env:
            - name: MILAN_OBRENOVIC_SECRET
              valueFrom:
                secretKeyRef:
                  # to find this key use `kubectl describe secret mysecret-from-file`
                  name: mysecret-from-file
                  key: secret
          command:
            - "sleep"
            - "3600"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: secrets
