apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 5
  revisionHistoryLimit: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # We want a maximum of 1 pod to be unavailable
      maxUnavailable: 1
      # Never have more than 1 pod above the desired state (must be <= number of replicas)
      maxSurge: 1
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world
      annotations:
        kubernetes.io/change-cause: "milanobrenovic/kubernetes:hello-world-v4"
    spec:
      containers:
        - name: hello-world
          image: milanobrenovic/kubernetes:hello-world-v4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  # This says it is tied to the template above
  # The `app` value in template needs to match the `app` value in selector
  selector:
    matchLabels:
      app: hello-world
